#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser()

parser.add_argument("-c", "--conflicts", help="Package name this one conflicts with (mocks)", action="append")
parser.add_argument("-p", "--provides", help="Package name this one provides (defaults to --conflicts value)", action="append")
parser.add_argument("package", help="Package name (use -fake ending)")
args = parser.parse_args()

if (args.provides is None):
    args.provides = args.conflicts

print "pkgname={0}".format(args.package)
print """\
pkgver=1
pkgrel=1
arch=('any')
license=('GPL')\
"""

def get_quoted(alist):
    return " ".join("'{0}'".format(p) for p in alist)

if args.provides is not None:
    print "provides=(" + get_quoted(args.provides) + ")"
if args.conflicts is not None:
    print "conflicts=(" + get_quoted(args.conflicts) + ")"

print """
package() {
    : Absolutely nothing to do
}
"""
